//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TravellingSalesmanOfIreland.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TravellingSalesmanOfIreland.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NAME : ei8246
        ///COMMENT : 8246 locations in Ireland
        ///COMMENT : Derived from National Imagery and Mapping Agency data
        ///TYPE : TSP
        ///DIMENSION : 8246
        ///EDGE_WEIGHT_TYPE : EUC_2D
        ///NODE_COORD_SECTION
        ///1 51445.0000 9479.4444
        ///2 51455.2778 9815.8333
        ///3 51462.2222 9433.6111
        ///4 51466.6667 9716.6667
        ///5 51468.6111 9810.0000
        ///6 51470.0000 9416.3889
        ///7 51472.7778 9768.8889
        ///8 51481.9444 9762.2222
        ///9 51483.3333 9350.0000
        ///10 51483.3333 9366.6667
        ///11 51483.6111 9783.0556
        ///12 51486.3889 9724.7222
        ///13 51487.7778 9348.0556
        ///14 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ei8246 {
            get {
                return ResourceManager.GetString("ei8246", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NAME : ei8246TestS10
        ///COMMENT : 8246 locations in Ireland
        ///COMMENT : Derived from National Imagery and Mapping Agency data
        ///TYPE : TSP
        ///DIMENSION : 8246
        ///EDGE_WEIGHT_TYPE : EUC_2D
        ///NODE_COORD_SECTION
        ///1 51445.0000 9479.4444
        ///2 51513.3333 9305.5556
        ///3 51550.0000 9133.3333
        ///4 51572.7778 9480.8333
        ///5 51573.0556 9118.8889
        ///6 51583.3333 9566.6667
        ///7 51705.5556 9068.0556
        ///8 51784.7222 8924.1667
        ///9 51877.7778 8798.0556
        ///10 52252.5000 6403.0556
        ///EOF.
        /// </summary>
        internal static string ei8246TestS10 {
            get {
                return ResourceManager.GetString("ei8246TestS10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NAME : ei8246
        ///COMMENT : 8246 locations in Ireland
        ///COMMENT : Derived from National Imagery and Mapping Agency data
        ///TYPE : TSP
        ///DIMENSION : 8246
        ///EDGE_WEIGHT_TYPE : EUC_2D
        ///NODE_COORD_SECTION
        ///18 51500.8333 9708.6111
        ///19 51505.8333 9350.8333
        ///20 51511.3889 9585.0000
        ///21 51513.3333 9305.5556
        ///22 51513.6111 9233.0556
        ///23 51515.8333 9193.8889
        ///24 51519.7222 9271.9444
        ///25 51520.8333 9656.1111
        ///26 51522.2222 9394.1667
        ///27 51522.7778 9502.5000
        ///28 51524.4444 9602.2222
        ///29 51526.3889 9183.3333
        ///30 51530.2778 9331 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ei8246TestS148 {
            get {
                return ResourceManager.GetString("ei8246TestS148", resourceCulture);
            }
        }
    }
}
